# Generated by Django 3.2.8 on 2021-10-17 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_auto_20211017_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('name', models.CharField(max_length=250, verbose_name='project name')),
                ('details', models.CharField(blank=True, max_length=250, null=True, verbose_name='project details')),
                ('file_1', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company', verbose_name='company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
