# Generated by Django 3.2.8 on 2021-10-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='state',
            field=models.CharField(choices=[('AP', 'Approved'), ('RE', 'Reprobate'), ('AC', 'Accepted'), ('IR', 'In review')], default='AP', max_length=2),
        ),
    ]
