# Generated by Django 3.2.8 on 2021-10-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='file_1',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='profile',
            name='file_2',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d'),
        ),
    ]
